NGINX 413 Payload Too Large Documentation
ibm-client-engineering/solution-filenet-aws pull request #54
Opened 2023-11-14 23:04 UTC by Myron-Woods-IBM

2023-11-15 04:52 UTC, faraz requested changes
Fix markdown formatting to keep it consistent

2023-11-15 04:52 UTC, faraz commented on docs/4-Transition/lessons.md
> +#### **Summary**
@Myron-Woods-IBM you dont need to bold `**summary** after establishing a headline in markdown using hashtags

2023-11-15 04:53 UTC, faraz commented
Reviewed - Requires changes

2023-11-15 16:05 UTC, Myron-Woods-IBM commented on docs/4-Transition/lessons.md
> +#### **Summary**
Updated and removed bold styling from headlines

2023-11-16 04:32 UTC, faraz approved these changes

2023-11-16 04:32 UTC, faraz commented
@Myron-Woods-IBM rebase and re-submit

2023-11-16 18:27 UTC, merged