added code block titles where relevant & some IER instructions formatting
ibm-client-engineering/solution-filenet-aws pull request #81
Opened 2023-11-28 22:51 UTC by gtiwari-ibm

2023-11-29 14:48 UTC, Manas-Jena-IBM commented on docs/3-Create/Deploy/ier.mdx
> +[Create the following objects stores](https://ibm-client-engineering.github.io/solution-filenet-aws/Create/Deploy/solution-deploy-operator#adding-object-stores) and configure them as mentioned. These
This works

2023-11-29 16:40 UTC, Manas-Jena-IBM reviewed
I found mostly formatting to the content . Like below . 
Line # 63
• Auto-destroy
- Auto-destroy
Line # 67 
1. Navigate to IER desktop and click on Configuration Tab. Select _Advanced Dispostion Schedules_ from dropdown as shown below.
1. Navigate to IER desktop and click on Configuration Tab. Select _Advanced Dispostion Schedules_ from the dropdown:

2023-11-29 17:02 UTC, gtiwari-ibm commented
made requested changes

2023-11-29 17:51 UTC, Manas-Jena-IBM requested changes
line# 154 - Please reword "Enabling Workflow Tab on Content Navigator" to Enabling web PD on ICN. We can add required screenshots to this section to follow easily 

Line # 156 Prerequsites should hold this 
1.Download Plugin from below url . Example url - host/port/peengine/plugins/CPEAppletsPlugin.jar 

2. Install PD Plugin - add or point to the instusctions we have on "how to add a plugin 
in ICN "

3. Add a section to **create custom menu** to show the web PD option in there . After this step Web PD should be visible on desktop menu where the "custom menu was added" 

OR 

we can alternatively say Web PD is no more supported where all the above steps would be obsolete.

2023-11-30 13:29 UTC, kramerro-ibm approved these changes

2023-11-30 14:44 UTC, Manas-Jena-IBM commented on docs/3-Create/Deploy/workflowsetup.mdx
>  1. Open up and log into the acce console
Reword like - Log in to ACCE

2023-11-30 15:51 UTC, Manas-Jena-IBM approved these changes
Looks good to me

2023-11-30 15:53 UTC, merged